-- Seed data: default intake questions and built-in exercises.
-- Applied by `supabase db reset` locally and `supabase db push --include-seed` on the hosted project.

-- Default intake questions (PLAN.md section 6.4). `level` on experience options maps to exercise
-- difficulty; health questions (limitations, limitations_detail) are shown only after consent.
insert into public.intake_questions (trainer_id, key, prompt, type, options, sort_order, required) values
  (null, 'goal', 'What''s your main goal?', 'single', '[
    {"value": "lose_fat", "label": "Lose fat"},
    {"value": "build_muscle", "label": "Build muscle"},
    {"value": "get_stronger", "label": "Get stronger"},
    {"value": "general_fitness", "label": "General fitness"},
    {"value": "mobility_rehab", "label": "Mobility / rehab"},
    {"value": "sport_specific", "label": "Sport-specific"}]', 1, true),
  (null, 'experience', 'How long have you been training?', 'single', '[
    {"value": "never", "label": "Never", "level": "beginner"},
    {"value": "under_6_months", "label": "Under 6 months", "level": "beginner"},
    {"value": "6_to_24_months", "label": "6–24 months", "level": "intermediate"},
    {"value": "over_2_years", "label": "2+ years", "level": "advanced"}]', 2, true),
  (null, 'days_per_week', 'How many days a week can you train?', 'number', '{"min": 1, "max": 7}', 3, true),
  (null, 'session_length', 'How long can each session be?', 'single', '[
    {"value": "20", "label": "20 minutes"},
    {"value": "30", "label": "30 minutes"},
    {"value": "45", "label": "45 minutes"},
    {"value": "60", "label": "60 minutes"},
    {"value": "90", "label": "90 minutes"}]', 4, true),
  (null, 'location', 'Where will you train?', 'single', '[
    {"value": "commercial_gym", "label": "Commercial gym"},
    {"value": "home_equipment", "label": "Home, with equipment"},
    {"value": "home_no_equipment", "label": "Home, no equipment"},
    {"value": "outdoors", "label": "Outdoors"}]', 5, true),
  (null, 'equipment', 'What equipment do you have access to?', 'multi', '[
    {"value": "barbell", "label": "Barbell"},
    {"value": "dumbbell", "label": "Dumbbells"},
    {"value": "kettlebell", "label": "Kettlebells"},
    {"value": "machine", "label": "Machines"},
    {"value": "cable", "label": "Cable station"},
    {"value": "band", "label": "Resistance bands"},
    {"value": "bodyweight", "label": "Bodyweight only"},
    {"value": "pull_up_bar", "label": "Pull-up bar"},
    {"value": "bench", "label": "Bench"},
    {"value": "cardio_machine", "label": "Cardio machines"},
    {"value": "other", "label": "Other"}]', 6, true),
  (null, 'limitations', 'Any injuries or areas to be careful with?', 'multi', '[
    {"value": "knees", "label": "Knees"},
    {"value": "lower_back", "label": "Lower back"},
    {"value": "shoulders", "label": "Shoulders"},
    {"value": "hips", "label": "Hips"},
    {"value": "wrists", "label": "Wrists"},
    {"value": "neck", "label": "Neck"},
    {"value": "none", "label": "None"}]', 7, false),
  (null, 'limitations_detail', 'Tell us more about any injuries (optional)', 'text', null, 8, false),
  (null, 'preferences', 'Exercises you enjoy or dislike (optional)', 'text', null, 9, false),
  (null, 'other', 'Anything else your trainer should know?', 'text', null, 10, false);

-- Built-in exercises (PLAN.md section 9.4).
insert into public.exercises (is_builtin, name, primary_muscle, equipment, tracking_type, difficulty, caution_tags) values
  (true, 'Barbell Back Squat', 'quads', '{barbell}', 'weight_reps', 'intermediate', '{knees,lower_back}'),
  (true, 'Goblet Squat', 'quads', '{dumbbell,kettlebell}', 'weight_reps', 'beginner', '{knees}'),
  (true, 'Leg Press', 'quads', '{machine}', 'weight_reps', 'beginner', '{knees}'),
  (true, 'Bodyweight Squat', 'quads', '{bodyweight}', 'bodyweight_reps', 'beginner', '{knees}'),
  (true, 'Walking Lunge', 'quads', '{dumbbell,bodyweight}', 'weight_reps', 'beginner', '{knees}'),
  (true, 'Bulgarian Split Squat', 'quads', '{dumbbell,bench}', 'weight_reps', 'intermediate', '{knees}'),
  (true, 'Leg Extension', 'quads', '{machine}', 'weight_reps', 'beginner', '{knees}'),
  (true, 'Romanian Deadlift', 'hamstrings', '{barbell,dumbbell}', 'weight_reps', 'intermediate', '{lower_back}'),
  (true, 'Conventional Deadlift', 'full_body', '{barbell}', 'weight_reps', 'advanced', '{lower_back}'),
  (true, 'Lying Leg Curl', 'hamstrings', '{machine}', 'weight_reps', 'beginner', '{}'),
  (true, 'Hip Thrust', 'glutes', '{barbell,bench}', 'weight_reps', 'intermediate', '{}'),
  (true, 'Glute Bridge', 'glutes', '{bodyweight}', 'bodyweight_reps', 'beginner', '{}'),
  (true, 'Standing Calf Raise', 'calves', '{machine,dumbbell}', 'weight_reps', 'beginner', '{}'),
  (true, 'Barbell Bench Press', 'chest', '{barbell,bench}', 'weight_reps', 'intermediate', '{shoulders}'),
  (true, 'Dumbbell Bench Press', 'chest', '{dumbbell,bench}', 'weight_reps', 'beginner', '{shoulders}'),
  (true, 'Incline Dumbbell Press', 'chest', '{dumbbell,bench}', 'weight_reps', 'beginner', '{shoulders}'),
  (true, 'Push-up', 'chest', '{bodyweight}', 'bodyweight_reps', 'beginner', '{wrists,shoulders}'),
  (true, 'Knee Push-up', 'chest', '{bodyweight}', 'bodyweight_reps', 'beginner', '{wrists}'),
  (true, 'Chest Fly (Cable)', 'chest', '{cable}', 'weight_reps', 'beginner', '{shoulders}'),
  (true, 'Pull-up', 'back', '{pull_up_bar}', 'bodyweight_reps', 'advanced', '{shoulders}'),
  (true, 'Assisted Pull-up', 'back', '{machine,band}', 'assisted_reps', 'beginner', '{shoulders}'),
  (true, 'Lat Pulldown', 'back', '{cable,machine}', 'weight_reps', 'beginner', '{}'),
  (true, 'Seated Cable Row', 'back', '{cable}', 'weight_reps', 'beginner', '{}'),
  (true, 'One-arm Dumbbell Row', 'back', '{dumbbell,bench}', 'weight_reps', 'beginner', '{}'),
  (true, 'Barbell Row', 'back', '{barbell}', 'weight_reps', 'intermediate', '{lower_back}'),
  (true, 'Band Pull-apart', 'shoulders', '{band}', 'reps_only', 'beginner', '{}'),
  (true, 'Overhead Press', 'shoulders', '{barbell}', 'weight_reps', 'intermediate', '{shoulders,lower_back}'),
  (true, 'Seated Dumbbell Shoulder Press', 'shoulders', '{dumbbell,bench}', 'weight_reps', 'beginner', '{shoulders}'),
  (true, 'Lateral Raise', 'shoulders', '{dumbbell,cable}', 'weight_reps', 'beginner', '{shoulders}'),
  (true, 'Face Pull', 'shoulders', '{cable,band}', 'weight_reps', 'beginner', '{}'),
  (true, 'Dumbbell Curl', 'biceps', '{dumbbell}', 'weight_reps', 'beginner', '{}'),
  (true, 'Hammer Curl', 'biceps', '{dumbbell}', 'weight_reps', 'beginner', '{}'),
  (true, 'Triceps Pushdown', 'triceps', '{cable}', 'weight_reps', 'beginner', '{}'),
  (true, 'Overhead Triceps Extension', 'triceps', '{dumbbell,cable}', 'weight_reps', 'beginner', '{shoulders}'),
  (true, 'Bench Dip', 'triceps', '{bench,bodyweight}', 'bodyweight_reps', 'intermediate', '{shoulders,wrists}'),
  (true, 'Plank', 'core', '{bodyweight}', 'duration', 'beginner', '{lower_back}'),
  (true, 'Side Plank', 'core', '{bodyweight}', 'duration', 'beginner', '{shoulders}'),
  (true, 'Dead Bug', 'core', '{bodyweight}', 'reps_only', 'beginner', '{}'),
  (true, 'Hanging Knee Raise', 'core', '{pull_up_bar}', 'bodyweight_reps', 'intermediate', '{shoulders}'),
  (true, 'Pallof Press', 'core', '{cable,band}', 'weight_reps', 'beginner', '{}'),
  (true, 'Kettlebell Swing', 'full_body', '{kettlebell}', 'weight_reps', 'intermediate', '{lower_back}'),
  (true, 'Farmer''s Carry', 'full_body', '{dumbbell,kettlebell}', 'distance_duration', 'beginner', '{}'),
  (true, 'Treadmill', 'cardio', '{cardio_machine}', 'distance_duration', 'beginner', '{knees}'),
  (true, 'Rowing Machine', 'cardio', '{cardio_machine}', 'distance_duration', 'beginner', '{lower_back}'),
  (true, 'Exercise Bike', 'cardio', '{cardio_machine}', 'distance_duration', 'beginner', '{}');
