-- Seed data: default intake questions and built-in exercises.
-- Applied by `supabase db reset` locally and `supabase db push --include-seed` on the hosted project.

-- Default intake questions (PLAN.md section 6.4). `level` on experience options maps to exercise
-- difficulty; health questions (limitations, limitations_detail) are shown only after consent.
insert into public.intake_questions (trainer_id, key, prompt, type, options, sort_order, required) values
  (null, 'goal', 'What''s your main goal?', 'single', '[
    {"value": "lose_fat", "label": "Lose fat"},
    {"value": "build_muscle", "label": "Build muscle"},
    {"value": "get_stronger", "label": "Get stronger"},
    {"value": "general_fitness", "label": "General fitness"},
    {"value": "mobility_rehab", "label": "Mobility / rehab"},
    {"value": "sport_specific", "label": "Sport-specific"}]', 1, true),
  (null, 'experience', 'How long have you been training?', 'single', '[
    {"value": "never", "label": "Never", "level": "beginner"},
    {"value": "under_6_months", "label": "Under 6 months", "level": "beginner"},
    {"value": "6_to_24_months", "label": "6–24 months", "level": "intermediate"},
    {"value": "over_2_years", "label": "2+ years", "level": "advanced"}]', 2, true),
  (null, 'days_per_week', 'How many days a week can you train?', 'number', '{"min": 1, "max": 7}', 3, true),
  (null, 'session_length', 'How long can each session be?', 'single', '[
    {"value": "20", "label": "20 minutes"},
    {"value": "30", "label": "30 minutes"},
    {"value": "45", "label": "45 minutes"},
    {"value": "60", "label": "60 minutes"},
    {"value": "90", "label": "90 minutes"}]', 4, true),
  (null, 'location', 'Where will you train?', 'single', '[
    {"value": "commercial_gym", "label": "Commercial gym"},
    {"value": "home_equipment", "label": "Home, with equipment"},
    {"value": "home_no_equipment", "label": "Home, no equipment"},
    {"value": "outdoors", "label": "Outdoors"}]', 5, true),
  (null, 'equipment', 'What equipment do you have access to?', 'multi', '[
    {"value": "barbell", "label": "Barbell"},
    {"value": "dumbbell", "label": "Dumbbells"},
    {"value": "kettlebell", "label": "Kettlebells"},
    {"value": "machine", "label": "Machines"},
    {"value": "cable", "label": "Cable station"},
    {"value": "band", "label": "Resistance bands"},
    {"value": "bodyweight", "label": "Bodyweight only"},
    {"value": "pull_up_bar", "label": "Pull-up bar"},
    {"value": "bench", "label": "Bench"},
    {"value": "cardio_machine", "label": "Cardio machines"},
    {"value": "other", "label": "Other"}]', 6, true),
  (null, 'limitations', 'Any injuries or areas to be careful with?', 'multi', '[
    {"value": "knees", "label": "Knees"},
    {"value": "lower_back", "label": "Lower back"},
    {"value": "shoulders", "label": "Shoulders"},
    {"value": "hips", "label": "Hips"},
    {"value": "wrists", "label": "Wrists"},
    {"value": "neck", "label": "Neck"},
    {"value": "none", "label": "None"}]', 7, false),
  (null, 'limitations_detail', 'Tell us more about any injuries (optional)', 'text', null, 8, false),
  (null, 'preferences', 'Exercises you enjoy or dislike (optional)', 'text', null, 9, false),
  (null, 'other', 'Anything else your trainer should know?', 'text', null, 10, false);

-- Built-in exercises, grouped by movement pattern and ordered from the most accessible
-- (chair, wall, bodyweight, bands) through dumbbells, kettlebells and a pull-up bar to gym kit.
insert into public.exercises
  (is_builtin, movement_pattern, name, primary_muscle, equipment, tracking_type, difficulty, caution_tags, description)
values
  -- squat
  (true, 'squat', 'Sit-to-Stand', 'quads', '{bodyweight}', 'bodyweight_reps', 'beginner', '{knees}', 'Stand up from a chair and sit back down with control. Use your hands on your thighs if needed.'),
  (true, 'squat', 'Wall Sit', 'quads', '{bodyweight}', 'duration', 'beginner', '{knees}', 'Back flat against a wall, slide down until knees are bent, and hold.'),
  (true, 'squat', 'Box Squat', 'quads', '{bodyweight,bench}', 'bodyweight_reps', 'beginner', '{knees}', 'Squat back until you lightly touch a bench or box, then stand.'),
  (true, 'squat', 'Bodyweight Squat', 'quads', '{bodyweight}', 'bodyweight_reps', 'beginner', '{knees}', null),
  (true, 'squat', 'Band Squat', 'quads', '{band}', 'reps_only', 'beginner', '{knees}', 'Stand on a band with the ends at your shoulders and squat.'),
  (true, 'squat', 'Goblet Squat', 'quads', '{dumbbell,kettlebell}', 'weight_reps', 'beginner', '{knees}', 'Hold one weight at your chest, elbows inside the knees at the bottom.'),
  (true, 'squat', 'Dumbbell Squat', 'quads', '{dumbbell}', 'weight_reps', 'beginner', '{knees}', 'A dumbbell in each hand at your sides.'),
  (true, 'squat', 'Jump Squat', 'quads', '{bodyweight}', 'bodyweight_reps', 'intermediate', '{knees}', 'Squat, then jump; land softly and go straight into the next rep.'),
  (true, 'squat', 'Assisted Pistol Squat', 'quads', '{bodyweight,band}', 'bodyweight_reps', 'intermediate', '{knees}', 'Single-leg squat holding a doorframe, post or band for balance.'),
  (true, 'squat', 'Pistol Squat', 'quads', '{bodyweight}', 'bodyweight_reps', 'advanced', '{knees}', 'Single-leg squat with the other leg held straight out in front.'),
  (true, 'squat', 'Smith Machine Squat', 'quads', '{machine}', 'weight_reps', 'beginner', '{knees}', null),
  (true, 'squat', 'Leg Press', 'quads', '{machine}', 'weight_reps', 'beginner', '{knees}', null),
  (true, 'squat', 'Hack Squat', 'quads', '{machine}', 'weight_reps', 'intermediate', '{knees}', null),
  (true, 'squat', 'Barbell Back Squat', 'quads', '{barbell}', 'weight_reps', 'intermediate', '{knees,lower_back}', null),
  (true, 'squat', 'Barbell Front Squat', 'quads', '{barbell}', 'weight_reps', 'advanced', '{knees,wrists}', null),
  -- lunge
  (true, 'lunge', 'Supported Split Squat', 'quads', '{bodyweight}', 'bodyweight_reps', 'beginner', '{knees}', 'Split stance, holding a chair or wall for balance; lower the back knee towards the floor.'),
  (true, 'lunge', 'Split Squat', 'quads', '{bodyweight,dumbbell}', 'bodyweight_reps', 'beginner', '{knees}', null),
  (true, 'lunge', 'Reverse Lunge', 'quads', '{bodyweight}', 'bodyweight_reps', 'beginner', '{knees}', 'Step back into a lunge; easier on the knees than stepping forward.'),
  (true, 'lunge', 'Weighted Reverse Lunge', 'quads', '{dumbbell,kettlebell}', 'weight_reps', 'beginner', '{knees}', null),
  (true, 'lunge', 'Step-up', 'quads', '{bench,bodyweight}', 'bodyweight_reps', 'beginner', '{knees}', 'Step onto a sturdy step, box or bench; start low.'),
  (true, 'lunge', 'Dumbbell Step-up', 'quads', '{dumbbell,bench}', 'weight_reps', 'beginner', '{knees}', null),
  (true, 'lunge', 'Lateral Lunge', 'quads', '{bodyweight}', 'bodyweight_reps', 'beginner', '{knees,hips}', 'Step wide to the side and sit back into that hip, keeping the other leg straight.'),
  (true, 'lunge', 'Walking Lunge', 'quads', '{dumbbell,bodyweight}', 'weight_reps', 'beginner', '{knees}', null),
  (true, 'lunge', 'Bulgarian Split Squat', 'quads', '{dumbbell,bench}', 'weight_reps', 'intermediate', '{knees}', 'Back foot raised on a bench.'),
  (true, 'lunge', 'Barbell Lunge', 'quads', '{barbell}', 'weight_reps', 'intermediate', '{knees}', null),
  -- hinge
  (true, 'hinge', 'Glute Bridge', 'glutes', '{bodyweight}', 'bodyweight_reps', 'beginner', '{}', null),
  (true, 'hinge', 'Single-leg Glute Bridge', 'glutes', '{bodyweight}', 'bodyweight_reps', 'beginner', '{}', null),
  (true, 'hinge', 'Banded Glute Bridge', 'glutes', '{band}', 'reps_only', 'beginner', '{}', 'Band just above the knees; push the knees out as you lift.'),
  (true, 'hinge', 'Dumbbell Glute Bridge', 'glutes', '{dumbbell}', 'weight_reps', 'beginner', '{}', 'Weight resting on the hips.'),
  (true, 'hinge', 'Dumbbell Hip Thrust', 'glutes', '{dumbbell,bench}', 'weight_reps', 'beginner', '{}', 'Upper back on a bench, weight on the hips.'),
  (true, 'hinge', 'Hip Thrust', 'glutes', '{barbell,bench}', 'weight_reps', 'intermediate', '{}', null),
  (true, 'hinge', 'Bodyweight Good Morning', 'hamstrings', '{bodyweight}', 'bodyweight_reps', 'beginner', '{lower_back}', 'Hands on hips, soft knees, push the hips back with a flat back. Teaches the hip hinge.'),
  (true, 'hinge', 'Band Good Morning', 'hamstrings', '{band}', 'reps_only', 'beginner', '{lower_back}', 'Band under the feet and behind the neck.'),
  (true, 'hinge', 'Pull-through', 'glutes', '{band,cable}', 'weight_reps', 'beginner', '{}', 'Face away from the anchor, hinge, then drive the hips forward.'),
  (true, 'hinge', 'Single-leg Romanian Deadlift', 'hamstrings', '{bodyweight}', 'bodyweight_reps', 'beginner', '{}', 'Hold a wall for balance if needed.'),
  (true, 'hinge', 'Kettlebell Deadlift', 'full_body', '{kettlebell,dumbbell}', 'weight_reps', 'beginner', '{lower_back}', 'Weight between the feet; a good first deadlift.'),
  (true, 'hinge', 'Romanian Deadlift', 'hamstrings', '{barbell,dumbbell}', 'weight_reps', 'intermediate', '{lower_back}', null),
  (true, 'hinge', 'Single-leg Dumbbell Romanian Deadlift', 'hamstrings', '{dumbbell,kettlebell}', 'weight_reps', 'intermediate', '{}', null),
  (true, 'hinge', 'Kettlebell Swing', 'full_body', '{kettlebell}', 'weight_reps', 'intermediate', '{lower_back}', null),
  (true, 'hinge', 'Back Extension', 'hamstrings', '{machine}', 'bodyweight_reps', 'beginner', '{lower_back}', 'On a back-extension (hyperextension) bench.'),
  (true, 'hinge', 'Trap Bar Deadlift', 'full_body', '{barbell}', 'weight_reps', 'intermediate', '{lower_back}', null),
  (true, 'hinge', 'Conventional Deadlift', 'full_body', '{barbell}', 'weight_reps', 'advanced', '{lower_back}', null),
  (true, 'hinge', 'Sumo Deadlift', 'full_body', '{barbell}', 'weight_reps', 'advanced', '{lower_back,hips}', null),
  (true, 'hinge', 'Nordic Hamstring Curl', 'hamstrings', '{bodyweight}', 'bodyweight_reps', 'advanced', '{knees}', 'Ankles anchored, lower your body forward as slowly as you can.'),
  -- push_horizontal
  (true, 'push_horizontal', 'Wall Push-up', 'chest', '{bodyweight}', 'bodyweight_reps', 'beginner', '{wrists}', 'Hands on a wall; step the feet further back to make it harder.'),
  (true, 'push_horizontal', 'Incline Push-up', 'chest', '{bench,bodyweight}', 'bodyweight_reps', 'beginner', '{wrists}', 'Hands on a bench, counter or step.'),
  (true, 'push_horizontal', 'Knee Push-up', 'chest', '{bodyweight}', 'bodyweight_reps', 'beginner', '{wrists}', null),
  (true, 'push_horizontal', 'Push-up', 'chest', '{bodyweight}', 'bodyweight_reps', 'beginner', '{wrists,shoulders}', null),
  (true, 'push_horizontal', 'Decline Push-up', 'chest', '{bench,bodyweight}', 'bodyweight_reps', 'intermediate', '{wrists,shoulders}', 'Feet raised on a bench or step.'),
  (true, 'push_horizontal', 'Banded Push-up', 'chest', '{band}', 'bodyweight_reps', 'intermediate', '{wrists,shoulders}', 'Band across the upper back, ends under the hands.'),
  (true, 'push_horizontal', 'Band Chest Press', 'chest', '{band}', 'reps_only', 'beginner', '{}', 'Band anchored behind you at chest height; can be done seated.'),
  (true, 'push_horizontal', 'Dumbbell Floor Press', 'chest', '{dumbbell}', 'weight_reps', 'beginner', '{}', 'Lying on the floor; the floor limits the range, which is kind to shoulders.'),
  (true, 'push_horizontal', 'Dumbbell Bench Press', 'chest', '{dumbbell,bench}', 'weight_reps', 'beginner', '{shoulders}', null),
  (true, 'push_horizontal', 'Incline Dumbbell Press', 'chest', '{dumbbell,bench}', 'weight_reps', 'beginner', '{shoulders}', null),
  (true, 'push_horizontal', 'Machine Chest Press', 'chest', '{machine}', 'weight_reps', 'beginner', '{}', null),
  (true, 'push_horizontal', 'Barbell Bench Press', 'chest', '{barbell,bench}', 'weight_reps', 'intermediate', '{shoulders}', null),
  (true, 'push_horizontal', 'Incline Barbell Bench Press', 'chest', '{barbell,bench}', 'weight_reps', 'intermediate', '{shoulders}', null),
  (true, 'push_horizontal', 'Assisted Dip', 'chest', '{machine,band}', 'assisted_reps', 'beginner', '{shoulders}', null),
  (true, 'push_horizontal', 'Dip', 'chest', '{other}', 'bodyweight_reps', 'advanced', '{shoulders}', 'On parallel bars or a dip station.'),
  -- push_vertical
  (true, 'push_vertical', 'Band Overhead Press', 'shoulders', '{band}', 'reps_only', 'beginner', '{shoulders}', 'Stand on the band and press overhead; can be done seated.'),
  (true, 'push_vertical', 'Seated Dumbbell Shoulder Press', 'shoulders', '{dumbbell,bench}', 'weight_reps', 'beginner', '{shoulders}', null),
  (true, 'push_vertical', 'Standing Dumbbell Shoulder Press', 'shoulders', '{dumbbell}', 'weight_reps', 'beginner', '{shoulders}', null),
  (true, 'push_vertical', 'Half-kneeling Landmine Press', 'shoulders', '{barbell}', 'weight_reps', 'beginner', '{}', 'One end of a barbell in a corner or landmine; a shoulder-friendly press.'),
  (true, 'push_vertical', 'Machine Shoulder Press', 'shoulders', '{machine}', 'weight_reps', 'beginner', '{shoulders}', null),
  (true, 'push_vertical', 'Pike Push-up', 'shoulders', '{bodyweight}', 'bodyweight_reps', 'intermediate', '{shoulders,wrists}', 'Hips high in an upside-down V; lower the head towards the floor.'),
  (true, 'push_vertical', 'Arnold Press', 'shoulders', '{dumbbell}', 'weight_reps', 'intermediate', '{shoulders}', null),
  (true, 'push_vertical', 'Kettlebell Press', 'shoulders', '{kettlebell}', 'weight_reps', 'intermediate', '{shoulders}', null),
  (true, 'push_vertical', 'Overhead Press', 'shoulders', '{barbell}', 'weight_reps', 'intermediate', '{shoulders,lower_back}', null),
  (true, 'push_vertical', 'Wall Handstand Push-up', 'shoulders', '{bodyweight}', 'bodyweight_reps', 'advanced', '{shoulders,wrists,neck}', null),
  -- pull_horizontal
  (true, 'pull_horizontal', 'Band Row', 'back', '{band}', 'reps_only', 'beginner', '{}', 'Band anchored in a door or around a post; can be done seated.'),
  (true, 'pull_horizontal', 'Band Pull-apart', 'shoulders', '{band}', 'reps_only', 'beginner', '{}', null),
  (true, 'pull_horizontal', 'Inverted Row', 'back', '{other,bodyweight}', 'bodyweight_reps', 'beginner', '{}', 'Under a low bar, Smith machine or sturdy table; walk the feet forward to make it harder.'),
  (true, 'pull_horizontal', 'One-arm Dumbbell Row', 'back', '{dumbbell,bench}', 'weight_reps', 'beginner', '{}', null),
  (true, 'pull_horizontal', 'Chest-supported Dumbbell Row', 'back', '{dumbbell,bench}', 'weight_reps', 'beginner', '{}', 'Lying face down on an incline bench; takes load off the lower back.'),
  (true, 'pull_horizontal', 'Seated Cable Row', 'back', '{cable}', 'weight_reps', 'beginner', '{}', null),
  (true, 'pull_horizontal', 'Machine Row', 'back', '{machine}', 'weight_reps', 'beginner', '{}', null),
  (true, 'pull_horizontal', 'Face Pull', 'shoulders', '{cable,band}', 'weight_reps', 'beginner', '{}', null),
  (true, 'pull_horizontal', 'Barbell Row', 'back', '{barbell}', 'weight_reps', 'intermediate', '{lower_back}', null),
  -- pull_vertical
  (true, 'pull_vertical', 'Band Lat Pulldown', 'back', '{band}', 'reps_only', 'beginner', '{}', 'Band anchored overhead, pull the elbows down to your sides.'),
  (true, 'pull_vertical', 'Straight-arm Pulldown', 'back', '{cable,band}', 'weight_reps', 'beginner', '{}', null),
  (true, 'pull_vertical', 'Dead Hang', 'back', '{pull_up_bar}', 'duration', 'beginner', '{shoulders}', 'Hang from the bar; keep the feet on a box to take some weight if needed.'),
  (true, 'pull_vertical', 'Lat Pulldown', 'back', '{cable,machine}', 'weight_reps', 'beginner', '{}', null),
  (true, 'pull_vertical', 'Assisted Pull-up', 'back', '{machine,band}', 'assisted_reps', 'beginner', '{shoulders}', null),
  (true, 'pull_vertical', 'Negative Pull-up', 'back', '{pull_up_bar}', 'bodyweight_reps', 'intermediate', '{shoulders}', 'Jump or step to the top, then lower yourself as slowly as you can.'),
  (true, 'pull_vertical', 'Chin-up', 'biceps', '{pull_up_bar}', 'bodyweight_reps', 'intermediate', '{shoulders}', 'Palms facing you.'),
  (true, 'pull_vertical', 'Pull-up', 'back', '{pull_up_bar}', 'bodyweight_reps', 'advanced', '{shoulders}', null),
  (true, 'pull_vertical', 'Weighted Pull-up', 'back', '{pull_up_bar,other}', 'weight_reps', 'advanced', '{shoulders}', 'Weight from a belt or held between the feet.'),
  -- carry
  (true, 'carry', 'Farmer''s Carry', 'full_body', '{dumbbell,kettlebell}', 'distance_duration', 'beginner', '{}', null),
  (true, 'carry', 'Suitcase Carry', 'core', '{dumbbell,kettlebell}', 'distance_duration', 'beginner', '{}', 'A weight in one hand only; stay tall without leaning.'),
  (true, 'carry', 'Overhead Carry', 'shoulders', '{dumbbell,kettlebell}', 'distance_duration', 'intermediate', '{shoulders}', null),
  -- core
  (true, 'core', 'Dead Bug', 'core', '{bodyweight}', 'reps_only', 'beginner', '{}', null),
  (true, 'core', 'Bird Dog', 'core', '{bodyweight}', 'reps_only', 'beginner', '{}', 'On hands and knees, reach opposite arm and leg out, keeping the hips level.'),
  (true, 'core', 'Kneeling Plank', 'core', '{bodyweight}', 'duration', 'beginner', '{}', 'A plank from the knees.'),
  (true, 'core', 'Plank', 'core', '{bodyweight}', 'duration', 'beginner', '{lower_back}', null),
  (true, 'core', 'Side Plank', 'core', '{bodyweight}', 'duration', 'beginner', '{shoulders}', null),
  (true, 'core', 'Lying Leg Raise', 'core', '{bodyweight}', 'bodyweight_reps', 'beginner', '{lower_back}', null),
  (true, 'core', 'Crunch', 'core', '{bodyweight}', 'bodyweight_reps', 'beginner', '{neck}', null),
  (true, 'core', 'Mountain Climber', 'core', '{bodyweight}', 'duration', 'beginner', '{wrists}', null),
  (true, 'core', 'Pallof Press', 'core', '{cable,band}', 'weight_reps', 'beginner', '{}', null),
  (true, 'core', 'Cable Woodchop', 'core', '{cable,band}', 'weight_reps', 'beginner', '{}', null),
  (true, 'core', 'Hollow Hold', 'core', '{bodyweight}', 'duration', 'intermediate', '{lower_back}', null),
  (true, 'core', 'Hanging Knee Raise', 'core', '{pull_up_bar}', 'bodyweight_reps', 'intermediate', '{shoulders}', null),
  (true, 'core', 'Cable Crunch', 'core', '{cable}', 'weight_reps', 'intermediate', '{}', null),
  (true, 'core', 'Hanging Leg Raise', 'core', '{pull_up_bar}', 'bodyweight_reps', 'advanced', '{shoulders,lower_back}', null),
  (true, 'core', 'Ab Wheel Rollout', 'core', '{other}', 'bodyweight_reps', 'advanced', '{lower_back,shoulders}', 'Start from the knees with a short range.'),
  -- isolation
  (true, 'isolation', 'Band Curl', 'biceps', '{band}', 'reps_only', 'beginner', '{}', null),
  (true, 'isolation', 'Dumbbell Curl', 'biceps', '{dumbbell}', 'weight_reps', 'beginner', '{}', null),
  (true, 'isolation', 'Hammer Curl', 'biceps', '{dumbbell}', 'weight_reps', 'beginner', '{}', null),
  (true, 'isolation', 'Cable Curl', 'biceps', '{cable}', 'weight_reps', 'beginner', '{}', null),
  (true, 'isolation', 'Barbell Curl', 'biceps', '{barbell}', 'weight_reps', 'beginner', '{}', null),
  (true, 'isolation', 'Machine Preacher Curl', 'biceps', '{machine}', 'weight_reps', 'beginner', '{}', null),
  (true, 'isolation', 'Band Triceps Pushdown', 'triceps', '{band}', 'reps_only', 'beginner', '{}', null),
  (true, 'isolation', 'Triceps Pushdown', 'triceps', '{cable}', 'weight_reps', 'beginner', '{}', null),
  (true, 'isolation', 'Overhead Triceps Extension', 'triceps', '{dumbbell,cable}', 'weight_reps', 'beginner', '{shoulders}', null),
  (true, 'isolation', 'Bench Dip', 'triceps', '{bench,bodyweight}', 'bodyweight_reps', 'intermediate', '{shoulders,wrists}', null),
  (true, 'isolation', 'Close-grip Push-up', 'triceps', '{bodyweight}', 'bodyweight_reps', 'intermediate', '{wrists}', null),
  (true, 'isolation', 'Skull Crusher', 'triceps', '{barbell,dumbbell,bench}', 'weight_reps', 'intermediate', '{}', null),
  (true, 'isolation', 'Close-grip Bench Press', 'triceps', '{barbell,bench}', 'weight_reps', 'intermediate', '{shoulders,wrists}', null),
  (true, 'isolation', 'Band Lateral Raise', 'shoulders', '{band}', 'reps_only', 'beginner', '{shoulders}', null),
  (true, 'isolation', 'Lateral Raise', 'shoulders', '{dumbbell,cable}', 'weight_reps', 'beginner', '{shoulders}', null),
  (true, 'isolation', 'Reverse Dumbbell Fly', 'shoulders', '{dumbbell}', 'weight_reps', 'beginner', '{}', null),
  (true, 'isolation', 'Reverse Pec Deck', 'shoulders', '{machine}', 'weight_reps', 'beginner', '{}', null),
  (true, 'isolation', 'Dumbbell Fly', 'chest', '{dumbbell,bench}', 'weight_reps', 'beginner', '{shoulders}', null),
  (true, 'isolation', 'Chest Fly (Cable)', 'chest', '{cable}', 'weight_reps', 'beginner', '{shoulders}', null),
  (true, 'isolation', 'Pec Deck', 'chest', '{machine}', 'weight_reps', 'beginner', '{shoulders}', null),
  (true, 'isolation', 'Clamshell', 'glutes', '{band,bodyweight}', 'reps_only', 'beginner', '{hips}', 'Lying on your side, knees bent, open the top knee; add a band to progress.'),
  (true, 'isolation', 'Banded Lateral Walk', 'glutes', '{band}', 'reps_only', 'beginner', '{}', 'Band around the legs, small steps sideways in a half-squat.'),
  (true, 'isolation', 'Cable Kickback', 'glutes', '{cable}', 'weight_reps', 'beginner', '{}', null),
  (true, 'isolation', 'Hip Abduction Machine', 'glutes', '{machine}', 'weight_reps', 'beginner', '{}', null),
  (true, 'isolation', 'Leg Extension', 'quads', '{machine}', 'weight_reps', 'beginner', '{knees}', null),
  (true, 'isolation', 'Lying Leg Curl', 'hamstrings', '{machine}', 'weight_reps', 'beginner', '{}', null),
  (true, 'isolation', 'Seated Leg Curl', 'hamstrings', '{machine}', 'weight_reps', 'beginner', '{}', null),
  (true, 'isolation', 'Sliding Leg Curl', 'hamstrings', '{bodyweight}', 'bodyweight_reps', 'intermediate', '{}', 'Lying on your back, heels on towels or sliders on a smooth floor; bridge up and curl the heels in.'),
  (true, 'isolation', 'Calf Raise', 'calves', '{bodyweight}', 'bodyweight_reps', 'beginner', '{}', 'Hold a wall or chair for balance; do it on a step for more range.'),
  (true, 'isolation', 'Standing Calf Raise', 'calves', '{machine,dumbbell}', 'weight_reps', 'beginner', '{}', null),
  (true, 'isolation', 'Seated Calf Raise', 'calves', '{machine}', 'weight_reps', 'beginner', '{}', null),
  -- cardio
  (true, 'cardio', 'Seated March', 'cardio', '{bodyweight}', 'duration', 'beginner', '{}', 'Sitting tall on a chair, lift the knees alternately; add arm swings.'),
  (true, 'cardio', 'Marching in Place', 'cardio', '{bodyweight}', 'duration', 'beginner', '{}', null),
  (true, 'cardio', 'Walk', 'cardio', '{bodyweight}', 'distance_duration', 'beginner', '{}', null),
  (true, 'cardio', 'Jumping Jacks', 'cardio', '{bodyweight}', 'duration', 'beginner', '{knees}', 'Step out to the side instead of jumping for a low-impact version.'),
  (true, 'cardio', 'Run', 'cardio', '{bodyweight}', 'distance_duration', 'intermediate', '{knees}', null),
  (true, 'cardio', 'Burpee', 'full_body', '{bodyweight}', 'bodyweight_reps', 'intermediate', '{knees,wrists,shoulders}', 'Step back instead of jumping for a lower-impact version.'),
  (true, 'cardio', 'Jump Rope', 'cardio', '{other}', 'duration', 'intermediate', '{knees}', null),
  (true, 'cardio', 'Exercise Bike', 'cardio', '{cardio_machine}', 'distance_duration', 'beginner', '{}', null),
  (true, 'cardio', 'Cross Trainer', 'cardio', '{cardio_machine}', 'distance_duration', 'beginner', '{}', 'Also called an elliptical.'),
  (true, 'cardio', 'Treadmill', 'cardio', '{cardio_machine}', 'distance_duration', 'beginner', '{knees}', null),
  (true, 'cardio', 'Rowing Machine', 'cardio', '{cardio_machine}', 'distance_duration', 'beginner', '{lower_back}', null),
  (true, 'cardio', 'Stair Climber', 'cardio', '{cardio_machine}', 'duration', 'intermediate', '{knees}', null);
